version: '3.3'
services:
    agent-service:
        restart: always 
        build: ./Agent-service 
        image: tjegou/agencycar-agent-service:1.0.0
        depends_on:
            - mongo
            - rabbitmq
        environment:
            - PORT=4000
            - MQ_HOST=rabbitmq
            - MONGO_HOST=mongo 
            - SLEEP_TIME=10000 
        ports: 
            - '4000-4050:4000' 

    customer-service:
        restart: always 
        build: ./Customer-service 
        image: tjegou/agencycar-customer-service:1.0.0
        depends_on:
            - mongo
            - rabbitmq
        environment:
            - MQ_HOST=rabbitmq
            - MONGO_HOST=mongo 
            - PREFETCH_COUNT=3 
            - SLEEP_TIME=10000 
        ports: 
            - '3000:3000'
            
    rabbitmq:
        ports:
            - '5672:5672'
            - '15672:15672'
        image: 'rabbitmq:3.11-management'
    
    mongo: 
        image: mongo:latest
        logging: 
            driver: none 
        ports:
            - '27017:27017'